trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:
- script: |
    echo {
    echo   "version": "%BUILD_BUILDNUMBER%",
    echo   "buildTimestamp": "%BUILD_BUILDID%",
    echo   "gitBranch": "%BUILD_SOURCEBRANCHNAME%",
    echo   "gitHash": "%BUILD_SOURCEVERSION%"
    echo } > "$(Build.ArtifactStagingDirectory)\version.json"

    echo "📦 Listing contents of build output folder:"
    dir "$(Build.ArtifactStagingDirectory)"

    echo "📄 Showing contents of version.json:"
    type "$(Build.ArtifactStagingDirectory)\version.json"
  displayName: 'Generate version.json and confirm'

