trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:
- powershell: |
    $timestamp = Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ"
    $json = @{
      version = "$(Build.BuildNumber)"
      buildTimestamp = $timestamp
      gitBranch = "$(Build.SourceBranchName)"
      gitHash = "$(Build.SourceVersion)"
    } | ConvertTo-Json -Compress
    $json | Out-File "$(Build.ArtifactStagingDirectory)\version.json" -Encoding utf8

    Write-Host "`n📦 Listing contents of build output folder:"
    Get-ChildItem -Path "$(Build.ArtifactStagingDirectory)"

    Write-Host "`n📄 Showing contents of version.json:"
    Get-Content -Path "$(Build.ArtifactStagingDirectory)\version.json"
  displayName: 'Generate version.json with UTC timestamp'
